name: Test Name
'on':
  push:
    branches:
    - main
    - dev
env:
  AWS_REGION: us-east-1
  ECS_TASK_DEFINITION: ECS_TASK
  CONTAINER_NAME: test-container
  ECS_SERVICE: ''
  ECS_CLUSTER: ''
jobs:
  Build-Python-Package-and-publish-it:
    runs-on: external-k8s
    steps:
    - uses: actions/checkout@v3
    - name: Set up Python
      uses: actions/setup-python@v3
      with:
        python-version: 3.x
    - name: Install dependencies
      run: 'python -m pip install --upgrade pip

        pip install build

        '
    - name: Build package
      run: python -m build
    - name: Publish package
      uses: pypa/gh-action-pypi-publish@27b31702a0e7fc50959f5ad993c78deac1bdfc29
      with:
        user: __token__
        password: ${{ secrets.PYPI_API_TOKEN }}
  Build-Python-App:
    steps:
    - uses: actions/checkout@v3
    - name: Set up Python
      uses: actions/setup-python@v3
      with:
        python-version: ${{ env.PYTHON_VERSION }}
    - name: Install dependencies
      run: 'python -m pip install --upgrade pip

        pip install flake8 pytest

        if [ -f requirements.txt ]; then pip install -r requirements.txt; fi

        '
    - name: Lint with flake8
      run: '# stop the build if there are Python syntax errors or undefined names

        flake8 . --count --select=E9,F63,F7,F82 --show-source --statistics

        # exit-zero treats all errors as warnings. The GitHub editor is 127 chars
        wide

        flake8 . --count --exit-zero --max-complexity=10 --max-line-length=127 --statistics

        '
    - name: Test with pytest
      run: 'pytest

        '
    runs-on: external-k8s
  Scan-code-with-Sonar:
    steps:
    - name: Analyze with SonarCloud
      uses: SonarSource/sonarcloud-github-action@de2e56b42aa84d0b1c5b622644ac17e505c9a049
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
      with:
        args: -Dsonar.projectKey= -Dsonar.organization=
    runs-on: external-k8s
